"""Initial migration: create cargo_manifest, admin_users, api_config tables

Revision ID: 001
Revises: 
Create Date: 2024-12-26 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create cargo_manifest table
    op.create_table('cargo_manifest',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('tracking_number', sa.String(length=50), nullable=False, comment='快递单号'),
        sa.Column('manifest_date', sa.Date(), nullable=False, comment='理货日期'),
        sa.Column('transport_code', sa.String(length=20), nullable=False, comment='运输代码'),
        sa.Column('customer_code', sa.String(length=20), nullable=False, comment='客户代码'),
        sa.Column('goods_code', sa.String(length=20), nullable=False, comment='货物代码'),
        sa.Column('package_number', sa.String(length=50), nullable=True, comment='集包单号'),
        sa.Column('weight', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='重量'),
        sa.Column('length', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='长度'),
        sa.Column('width', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='宽度'),
        sa.Column('height', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='高度'),
        sa.Column('special_fee', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='特殊费用'),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tracking_number')
    )
    
    # Create indexes for cargo_manifest
    op.create_index('idx_tracking_number', 'cargo_manifest', ['tracking_number'], unique=False)
    op.create_index('idx_package_number', 'cargo_manifest', ['package_number'], unique=False)
    
    # Create admin_users table
    op.create_table('admin_users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
        sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
        sa.Column('last_login', sa.TIMESTAMP(), nullable=True, comment='最后登录时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    
    # Create api_config table
    op.create_table('api_config',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('config_key', sa.String(length=50), nullable=False, comment='配置键'),
        sa.Column('config_value', sa.String(length=255), nullable=False, comment='配置值'),
        sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('config_key')
    )
    
    # Insert initial API configuration data
    op.execute("""
        INSERT INTO api_config (config_key, config_value, description) VALUES
        ('kuaidi100_key', 'fypLxFrg3636', '快递100授权key'),
        ('kuaidi100_customer', '3564B6CF145FA93724CE18C1FB149036', '快递100客户标识'),
        ('kuaidi100_secret', '8fa1052ba57e4d9ca0427938a77e2e30', '快递100密钥'),
        ('kuaidi100_userid', 'a1ffc21f3de94cf5bdd908faf3bbc81d', '快递100用户ID')
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_config')
    op.drop_table('admin_users')
    op.drop_index('idx_package_number', table_name='cargo_manifest')
    op.drop_index('idx_tracking_number', table_name='cargo_manifest')
    op.drop_table('cargo_manifest')
    # ### end Alembic commands ###